feat: 채팅 서비스 연동
gnimty/frontend-gnimty pull request #106
Opened 2024-02-01 08:22 UTC by LucetTin5

## Summary

- 채팅 서비스 연동

## Describe your changes

- 챗 컴포넌트들 생성
- ChatContext를 통해 AuthProvider 아래에 ChatProvider를 추가하였습니다
- ChatProvider를 통해 다른 페이지들에서도(홈 등) 채팅을 생성하도록 하게 설정

TODO
- user 정보를 받아 표시하는 부분 수정 필요 (솔로랭크/자유랭크 정보, 디테일한 유저정보 등)

2024-02-02 11:01 UTC, jun2077681 requested changes

2024-02-02 11:01 UTC, jun2077681 commented on src/components/chat/ChatInput.tsx
> +  const { currentUserId, chatClient, selectedChatRoomNo } = useChatContext();
lint warning 있네요

2024-02-02 11:01 UTC, jun2077681 commented on src/components/chat/ChatInput.tsx
> +    if (chat) {
이거 chat 이 빈 문자열일 때는 문제 없나요?

2024-02-02 11:01 UTC, jun2077681 commented on src/components/chat/ChatInput.tsx
> +    chatRef.current!.value = '';
!. 쓰는것보다 그냥 if 문 안에 넣는게 좋을 것 같아요

2024-02-02 11:01 UTC, jun2077681 commented on src/components/chat/ChatList.tsx
> +import { useContext, useEffect, useState } from 'react';
여기도 lint error

2024-02-02 11:01 UTC, jun2077681 commented on src/components/chat/CurrentChat.tsx
> +  }, [chats]);
여기 deps는 일부러 안넣으신건지 체크해주세용

2024-02-02 11:01 UTC, jun2077681 commented on src/components/chat/CurrentChat.tsx
> +    console.log(chats);
console.log
아래쪽에도 있던데 찾아서 지워주세요

2024-02-02 11:01 UTC, jun2077681 commented on src/components/chat/types.ts
> +// types for chat
공통으로 관리되던 타입이랑 전부 별개의 타입인가요?
types는 types 폴더에 따로 관리할 필요가 있겠네요.. 나중에 얘기해봐요 @nix6839

2024-02-02 11:01 UTC, jun2077681 commented on src/components/pages/main/UserCardLandscape.tsx
> +    if (disclosure.isOpen !== true) {
!disclosure.isOpen

2024-02-02 11:01 UTC, jun2077681 commented on src/contexts/ChatContext.ts
> +  const handleUpdate = <T extends UpdateActions>(type: T, data: DataType<T>) => {
여기도 lint error네요
useCallback으로 감싸달라고 합니다

2024-02-02 11:01 UTC, jun2077681 commented on src/styles/scrollbar.css
> +::-webkit-scrollbar {
이 부분 전체 스크롤에 영향 주는거일텐데 괜찮..나요?
전체에 주는거면 global 쪽에 쓰셔도

2024-02-02 11:15 UTC, LucetTin5 commented on src/styles/scrollbar.css
> +::-webkit-scrollbar {
이렇게 써버리면 전체에 영향을 줘버리겠네요 채팅창 스크롤바 요청드려서 받았던 부분인데 전체에 줘도 되려나요

2024-02-02 11:16 UTC, LucetTin5 commented on src/contexts/ChatContext.ts
> +  const handleUpdate = <T extends UpdateActions>(type: T, data: DataType<T>) => {
useMemo, useCallback은 성능에 진짜 영향이 있는 게 아니라면 안 쓰는걸 react에서도 추천하는 것 같아 사용하지 않으려고 하는데 어떠신가요?

2024-02-02 11:17 UTC, LucetTin5 commented on src/components/chat/types.ts
> +// types for chat
stomp쪽이라 뭔가 api/types에 두기는 안어울리는 것 같아 우선은 해당 위치에 두었습니다

2024-02-02 11:17 UTC, LucetTin5 commented on src/components/chat/CurrentChat.tsx
> +  }, [chats]);
테스트용 콘솔로그에 넣었다가 지우는걸 빼먹었네요

2024-02-02 11:18 UTC, LucetTin5 commented on src/components/chat/ChatInput.tsx
> +    if (chat) {
생각을 못했네요

2024-02-02 11:39 UTC, jun2077681 commented on src/contexts/ChatContext.ts
> +  const handleUpdate = <T extends UpdateActions>(type: T, data: DataType<T>) => {
해당 부분은 경고 메세지 보면 성능에 영향 있어보이는데 아닌가요

2024-02-02 12:13 UTC, LucetTin5 commented on src/contexts/ChatContext.ts
> +  const handleUpdate = <T extends UpdateActions>(type: T, data: DataType<T>) => {
해당 함수만의 성능 측정까지는 현재 방법은 모르겠습니다만, 해당 컨텍스트가 useEffect 여럿에 걸쳐 사용되고 있는 등 문제가 될 소지는 있다고 생각합니다.
메모이제이션 처리 해두겠습니다!

2024-02-14 10:06 UTC, nix6839 approved these changes

2024-02-14 10:16 UTC, jun2077681 approved these changes

2024-02-14 10:31 UTC, merged