feat: champion detail page api connection
gnimty/frontend-gnimty pull request #165
Opened 2024-03-27 07:29 UTC by LucetTin5

## Summary

- 챔피언 디테일 페이지 api 연동입니다
- 하단의 Tip 영역은 해당 부분 api 수정 중이라 하셔서 추후 작업 예정입니다

## Describe your changes

- 

### issues

- detail page 초기 진입, 포지션 변경 시 로딩이 느립니다
- 소환사 주문 ~ 신발 부분의 레이아웃 크기 조정을 진행해야 합니다

2024-03-27 21:03 UTC, nix6839 requested changes

2024-03-27 21:03 UTC, nix6839 commented on src/components/pages/champions/ChampionBasicInfo.tsx
> +            }
```suggestion
            const selectedLane = ['UNKNOWN', 'ALL', ''].includes(lane) ? index === 0 :  laneSelectRate.lane === lane;
```

2024-03-27 21:03 UTC, nix6839 commented on src/components/pages/champions/ChampionBasicInfo.tsx
> +            }
혹시 이 부분의 컨텍스트에 대해서 설명해주실 수 있으신가요?

2024-03-27 21:03 UTC, nix6839 commented on src/components/pages/champions/DetailPage.tsx
> +  }, [championEnName, router]);
- `router.push()` 보단 `router.replace()`가 나을 것 같습니다!
- `find()` 보단 `some()`이 이 상황에 좀 더 알맞는 함수인 것 같습니다!
- `championDetailQuery`의 응답 결과를 통해 404 여부를 판별하는 게 낫지 않을까요?

2024-03-28 01:06 UTC, LucetTin5 commented on src/components/pages/champions/ChampionBasicInfo.tsx
> +            }
DetailPage에서 filter 값으로 존재하는 lane을 기준으로, 필터값이 앞의 셋에 해당하는 경우, 기본값으로 챔피언 디테일 정보에 담긴 lane 중 첫번째를 기본 선택된 값으로 하라는 내용입니다

2024-03-28 01:20 UTC, LucetTin5 commented on src/components/pages/champions/DetailPage.tsx
> +  }, [championEnName, router]);
BaseResponse를 extends하여 변경하도록 하겠습니다

2024-03-28 02:44 UTC, nix6839 commented on src/components/pages/champions/ChampionBasicInfo.tsx
> +            }
아 `<DetailPage />` 컴포넌트를 보고나니 이해가 되네요 `'UNKNOWN'`이나 `'ALL'` 값은 올 일이 없을 거 같아서 뺴도 될 거 같긴 한데 혹시 모르니까 그냥 넣어놔도 되긴하겠네요

2024-03-28 02:47 UTC, nix6839 commented on src/components/pages/champions/DetailPage.tsx
> +  }, [championEnName, router]);
음 404 같은 경우엔 에러로 처리가 되어서 현재 코드로도 작동하는지는 모르겠는데 설령 작동하더라도 https://github.com/gnimty/frontend-gnimty/pull/160/files#diff-a3561aa5723910df7d3911b007edf4cf90864269e9b123412728e6eea767c562R243 이 코드 처럼 `data`가 아니라 `error`를 통해서 처리 하는게 명확할 것 같아요!

2024-03-28 04:27 UTC, nix6839 commented on src/components/pages/champions/DetailPage.tsx
> +  }, [championEnName, router]);
```js
    if (error?.response?.data.status.code === 404) {
      router.replace('/404');
    }
```
로 단순하게 처리 안한 이유가 있나요?

2024-03-28 04:34 UTC, LucetTin5 commented on src/components/pages/champions/DetailPage.tsx
> +  }, [championEnName, router]);
간단한 방법이 있었군요

2024-03-28 04:56 UTC, nix6839 approved these changes

2024-03-28 05:07 UTC, merged