fix: recommend popup
gnimty/frontend-gnimty pull request #188
Opened 2024-04-26 08:20 UTC by LucetTin5

## Summary

- api, 쿼리 수정
- like icon 컴포넌트 분리

## Describe your changes

- 다른 api를 사용하고 있어서 변경했습니다
- 불러와지지 않았을 경우 크래시가 나는 부분이 있어 확인절차를 추가했습니다

2024-04-26 08:54 UTC, nix6839 requested changes

2024-04-26 08:54 UTC, nix6839 commented on src/components/recommends/Recommends.tsx
> +  }, [queueType, isOpen]);
```suggestion
  const handleQueueTypeChange = (newValue: Omit<GameMode, 'BLIND'>) => {
    if (value !== newValue) {
      setPage(0);
    }
    setQueueType(value);
  };
```

2024-04-27 15:07 UTC, nix6839 requested changes

2024-04-27 15:07 UTC, nix6839 commented on src/components/recommends/SummonerCard.tsx
> +  }, [memberLikeAsync, memberId]);
이 부분 `memberLikeAsync`가 실제로 작동 안하지 않나요?

2024-04-27 15:14 UTC, LucetTin5 commented on src/components/recommends/SummonerCard.tsx
> +  }, [memberLikeAsync, memberId]);
아 즉시실행부분을 빼먹었네요

2024-04-27 15:41 UTC, LucetTin5 commented on src/components/recommends/SummonerCard.tsx
> +  }, [memberLikeAsync, memberId]);
다시 생각해보니까 이건 빠지는게 맞겠네요 좋아요를 눌렀던 회원은 응답에 오지 않는다고 하셨으니 이미 눌렀었는지를 확인할 필요가 없네요

2024-04-28 01:45 UTC, nix6839 approved these changes

2024-04-28 01:49 UTC, merged