feat: gnimty info tab api connection
gnimty/frontend-gnimty pull request #205
Opened 2024-05-12 10:33 UTC by LucetTin5

## Summary

- puuid를 이용하여 그님티 정보를 불러오는 api를 연결했습니다

2024-05-12 10:46 UTC, nix6839 requested changes

2024-05-12 10:46 UTC, nix6839 commented on src/apis/queries/memberProfileQuery.ts
>  const memberProfileQuery = (options: Options) =>
이 부분은 문서화와 코드 스타일의 영역인 거 같긴한데 `puuid`를 옵셔널로 받지 말고 `options`자체를 옵셔널로 받게 해서 `enabled` 여부를 제어하는 게 낫지 않을까요?

2024-05-12 10:56 UTC, LucetTin5 commented on src/apis/queries/memberProfileQuery.ts
>  const memberProfileQuery = (options: Options) =>
options를 옵셔널로 받는다는건 아래처럼 나타낸다는 걸까요?
```ts
// Summoner.tsx
// summonersMatchQuery -> data
const profileQueryOptions = data?.data.summoner.puuid ? { puuid: data?.data.summoner.puuid } : undefined;
  const { data: memberProfileData } = useQuery(memberProfileQuery(profileQueryOptions));

// query.ts
const memberProfileQuery = (options?: Options) =>
  queryOptions({
    queryKey: ['memberProfile', options],
    async queryFn() {
      const res = await httpRequest.get<MemberProfileResponse>(`/community/members/${options?.puuid}`);
      return res.data;
    },
    retry(failureCount, error) {
      if (error.response?.data.status.code === 404) {
        return false;
      }
      return failureCount <= 2;
    },
    enabled: !!options?.puuid,
  });
```

2024-05-12 11:00 UTC, nix6839 commented on src/apis/queries/memberProfileQuery.ts
>  const memberProfileQuery = (options: Options) =>
```ts
// Summoner.tsx
// summonersMatchQuery -> data
  const { data: memberProfileData } = useQuery(data !== undefined ? { puuid: data?.data.summoner.puuid } : undefined));
```

```ts
// query.ts
const memberProfileQuery = (options?: Options) =>
  queryOptions({
    queryKey: ['memberProfile', options],
    async queryFn() {
      const res = await httpRequest.get<MemberProfileResponse>(`/community/members/${options?.puuid}`);
      return res.data;
    },
    retry(failureCount, error) {
      if (error.response?.data.status.code === 404) {
        return false;
      }
      return failureCount <= 2;
    },
    enabled: options !== undefined,
  });
```

넵 이렇게요

2024-05-12 11:18 UTC, LucetTin5 commented on src/apis/queries/memberProfileQuery.ts
>  const memberProfileQuery = (options: Options) =>
이 방향으로 진행하다 보니까, member가 아닌 경우에도 세 값을 null/null/null로 돌려주는데 회원인 경우에도 null/null/null일 수가 있어서 비회원 처리를 다르게 해달라고 말씀드려야겠습니다

2024-05-13 00:31 UTC, nix6839 requested changes

2024-05-13 00:31 UTC, nix6839 commented on src/apis/queries/memberProfileQuery.ts
> +    enabled: options?.puuid !== undefined,
```suggestion
    enabled: options !== undefined,
```

2024-05-13 00:31 UTC, nix6839 commented on src/components/pages/summoners/[summonerTagName]/Summoner.tsx
> +    memberProfileQuery(data?.data.summoner.puuid ? { puuid: data?.data.summoner.puuid } : undefined),
```suggestion
    memberProfileQuery(data !== undefined ? { puuid: data.data.summoner.puuid } : undefined),
```

또는

```suggestion
    memberProfileQuery(status === 'success' ? { puuid: data.data.summoner.puuid } : undefined),
```

2024-05-13 00:35 UTC, nix6839 approved these changes

2024-05-13 00:37 UTC, merged